### ISSUE TITLE
Problema con collectstatic

### ISSUE THREAD

**Issue by enricofer** [italia/design-django-theme#10]
eseguendo `python manage.py collectstatic` ottengo la seguente eccezione:

```
Post-processing 'css/vendor/owl.carousel.min.css' failed!

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 331, in _post_process
    content = pattern.sub(converter, content)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 208, in converter
    hashed_url = self._url(
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 145, in _url
    hashed_name = hashed_name_func(*args)
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 381, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/dati/archiviazione/virtual_envs/testcms/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 106, in hashed_name
    raise ValueError(
ValueError: The file 'css/vendor/owl.video.play.png' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f5477827490>.
```

Ho risolto cercando in rete il file `owl.video.play.png` e copiandolo manualmente nella directory templates/css/vendor presente nel modulo

**Comment by francesco-filicetti** [comment]
Ciao @enricofer,
è stata rilasciata la nuova versione della libreria, basata su Bootstrap Italia 2.0.2. Con questo aggiornamento viene abbandonato OWL Carousel che, quindi, dev'essere incluso separatamente nei progetti.
